"""empty message

Revision ID: 27deabb2f5c1
Revises: 4a12f84b5c9a
Create Date: 2023-06-12 22:40:55.637479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27deabb2f5c1'
down_revision = '4a12f84b5c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_index('ix_interest_theme')
        batch_op.create_index(batch_op.f('ix_interest_theme'), ['theme'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_theme'))
        batch_op.create_index('ix_interest_theme', ['theme'], unique=False)

    # ### end Alembic commands ###
